# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio6/studio6.cache/wt [current_project]
set_property parent.project_path C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio6/studio6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_6/project_6.srcs/sources_1/new/Display_Driver4.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_6/project_6.srcs/sources_1/new/Display_Driver3.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_6/project_6.srcs/sources_1/new/Counter_4bit.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_6/project_6.srcs/sources_1/new/clock_divider.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_6/project_6.srcs/sources_1/new/Display_Driver2.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_6/project_6.srcs/sources_1/new/Display_Driver1.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/LEDdisplay.vhd
  C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/project_6/project_6.srcs/sources_1/new/Toplevel.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio6/studio6.srcs/constrs_1/new/studio6_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/flandc/OneDrive/MyFiles/@RPI/CoCO/Vivado_Projects/studio6/studio6.srcs/constrs_1/new/studio6_constraints.xdc]


synth_design -top Toplevel -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Toplevel.dcp

catch { report_utilization -file Toplevel_utilization_synth.rpt -pb Toplevel_utilization_synth.pb }
